version: 2
workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 7"
          filters:
            branches:
              only:
                - master
    jobs:
      - debian_builder

  build_and_test:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: casualjim/rs-rapid-builder
    steps:
      - checkout

      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile

      - restore_cache:
          keys:
          - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

      - run:
          name: Build all targets
          command: cargo build --all --all-targets

      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

      - run:
          name: Run unit tests
          command: cargo test --all
          no_output_timeout: 30m

#      - run:
#          name: Run unit tests
#          command: cargo junit --name /usr/share/testresults/results.xml
#          no_output_timeout: 30m

#      - run:
#          name: Run unit tests with race detection
#          command: cargo tarpaulin --out Xml
#          no_output_timeout: 30m

      - run:
          name: Submit coverage results
          command: bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: /usr/share/testresults

  debian_builder:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build debian builder image
          command: |
            docker build --pull -t casualjim/rs-rapid-builder .circleci/builder
            echo $DOCKER_PASS | docker login -u $API_USERNAME --password-stdin
            docker push casualjim/rs-rapid-builder
